version: "3.6"

services:
  web:
    build: .
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 80
    volumes:
      - ./:/usr/src/app/
    ports:
      - "1337:80"
    environment:
      - DEBUG=1
    depends_on:
      - redis
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  celery:
    build: .
    command: poetry run celery -A app.main.celery worker -l info
    volumes:
      - ./:/usr/src/app/
    environment:
      - DEBUG=1
    depends_on:
      - redis
