version: "3.6"

services:
  web:
    build: .
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 80
    volumes:
      - ./:/usr/src/app/
    ports:
      - "1337:80"
    environment:
      - DEBUG=1
    depends_on:
      - redis
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  celery_resize:
    build: .
    command: poetry run celery -A app.main.celery worker -l info -Q resize -n resize
    volumes:
      - ./:/usr/src/app/
    environment:
      - DEBUG=1
    depends_on:
      - redis
  celery_convert:
    build: .
    command: poetry run celery -A app.main.celery worker -l info -Q convert -n convert
    volumes:
      - ./:/usr/src/app/
    environment:
      - DEBUG=1
    depends_on:
      - redis
  celery_beat:
    build: .
    command: poetry run celery -A app.main.celery beat -l info
    volumes:
      - ./:/usr/src/app/
    env_file:
      - .env
    depends_on:
      - redis
      - celery_convert
  flower:
    build: .
    command: poetry run celery -A app.main.celery flower
    volumes:
      - ./:/usr/src/app/
    env_file:
      - .env
    ports:
      - 5557:5555
    depends_on:
      - redis
      - celery_convert
      - celery_resize

